"""add_target_price_to_shop_links

Revision ID: 63361ec60a0e
Revises: ad00f2a06cb0
Create Date: 2026-06-29 12:36:24.726664+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '63361ec60a0e'
down_revision: Union[str, None] = 'ad00f2a06cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_links', sa.Column('target_price', sa.Float(), nullable=True))
    op.add_column('shop_links', sa.Column('target_price_per_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_links', 'target_price_per_kg')
    op.drop_column('shop_links', 'target_price')
    # ### end Alembic commands ###
