"""add_dual_color_support

Revision ID: fc5b2c227b07
Revises: a9f8e7d6c5b4
Create Date: 2026-07-02 10:59:18.868995+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc5b2c227b07'
down_revision: Union[str, None] = 'a9f8e7d6c5b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filament_products', sa.Column('color_name_2', sa.String(length=64), nullable=True))
    op.add_column('filament_products', sa.Column('color_hex_2', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filament_products', 'color_hex_2')
    op.drop_column('filament_products', 'color_name_2')
    # ### end Alembic commands ###
