"""add_price_snapshots_shop_rules

Revision ID: ad00f2a06cb0
Revises: bc4d6d0b4e99
Create Date: 2026-06-29 11:37:03.748734+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ad00f2a06cb0'
down_revision: Union[str, None] = 'bc4d6d0b4e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=False),
    sa.Column('price_selector', sa.String(length=256), nullable=True),
    sa.Column('title_selector', sa.String(length=256), nullable=True),
    sa.Column('availability_selector', sa.String(length=256), nullable=True),
    sa.Column('price_regex', sa.String(length=256), nullable=True),
    sa.Column('availability_regex', sa.String(length=256), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('test_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_rules_domain'), 'shop_rules', ['domain'], unique=True)
    op.create_table('price_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_link_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('shipping_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('availability', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['shop_link_id'], ['shop_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_snapshots_captured_at'), 'price_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_price_snapshots_shop_link_id'), 'price_snapshots', ['shop_link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_snapshots_shop_link_id'), table_name='price_snapshots')
    op.drop_index(op.f('ix_price_snapshots_captured_at'), table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_shop_rules_domain'), table_name='shop_rules')
    op.drop_table('shop_rules')
    # ### end Alembic commands ###
