"""initial

Revision ID: 626bbe7fd55a
Revises: 
Create Date: 2026-06-29 09:53:02.220258+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '626bbe7fd55a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('website', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_name'), 'manufacturers', ['name'], unique=True)
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('shop_name', sa.String(length=128), nullable=False),
    sa.Column('order_number', sa.String(length=64), nullable=True),
    sa.Column('shipping_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_purchase_date'), 'purchases', ['purchase_date'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', 'viewer', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('filament_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('material', sa.String(length=64), nullable=False),
    sa.Column('color_name', sa.String(length=64), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('diameter_mm', sa.Float(), nullable=False),
    sa.Column('nominal_weight_g', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filament_products_material'), 'filament_products', ['material'], unique=False)
    op.create_table('purchase_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('filament_product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('spool_weight_g', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['filament_product_id'], ['filament_products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filament_product_id', sa.Integer(), nullable=False),
    sa.Column('purchase_line_id', sa.Integer(), nullable=True),
    sa.Column('spool_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('neu', 'geoeffnet', 'fast_leer', 'leer', 'archiviert', name='spoolstatus'), nullable=False),
    sa.Column('initial_weight_g', sa.Float(), nullable=False),
    sa.Column('remaining_weight_g', sa.Float(), nullable=False),
    sa.Column('storage_location', sa.String(length=128), nullable=True),
    sa.Column('storage_status', sa.Enum('offen', 'verschlossen', 'vakuumiert', 'drybox', 'unbekannt', name='storagestatus'), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('last_dried_at', sa.DateTime(), nullable=True),
    sa.Column('last_weight_update_source', sa.String(length=64), nullable=True),
    sa.Column('last_weight_update_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filament_product_id'], ['filament_products.id'], ),
    sa.ForeignKeyConstraint(['purchase_line_id'], ['purchase_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spools_spool_code'), 'spools', ['spool_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spools_spool_code'), table_name='spools')
    op.drop_table('spools')
    op.drop_table('purchase_lines')
    op.drop_index(op.f('ix_filament_products_material'), table_name='filament_products')
    op.drop_table('filament_products')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_purchases_purchase_date'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_manufacturers_name'), table_name='manufacturers')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
