"""add_shop_link

Revision ID: bc4d6d0b4e99
Revises: 626bbe7fd55a
Create Date: 2026-06-29 11:26:15.916977+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc4d6d0b4e99'
down_revision: Union[str, None] = '626bbe7fd55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filament_product_id', sa.Integer(), nullable=False),
    sa.Column('shop_name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('package_weight_g', sa.Integer(), nullable=False),
    sa.Column('manual_price', sa.Float(), nullable=False),
    sa.Column('shipping_price', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filament_product_id'], ['filament_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_links')
    # ### end Alembic commands ###
