"""add_price_alert_events

Revision ID: 8c44485082dc
Revises: 63361ec60a0e
Create Date: 2026-06-29 12:49:15.690857+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8c44485082dc'
down_revision: Union[str, None] = '63361ec60a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_link_id', sa.Integer(), nullable=False),
    sa.Column('price_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['price_snapshot_id'], ['price_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shop_link_id'], ['shop_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alert_events_created_at'), 'price_alert_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_price_alert_events_shop_link_id'), 'price_alert_events', ['shop_link_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_alert_events_shop_link_id'), table_name='price_alert_events')
    op.drop_index(op.f('ix_price_alert_events_created_at'), table_name='price_alert_events')
    op.drop_table('price_alert_events')
    # ### end Alembic commands ###
